mdb:
  image: pfadipatria/hitobito
  links:
   - elasticsearch:es
  environment:
    RAILS_ENV: production
    RAILS_HOST_NAME: mdb-test.pfadipatria.com
    RAILS_HOST_SSL: false
    RAILS_SECRET_TOKEN:
    RAILS_DB_NAME: mdb_test
    RAILS_DB_USERNAME: mdb_test
    RAILS_DB_PASSWORD:
    RAILS_DB_HOST: mysql02
    RAILS_DB_PORT: 3306
    RAILS_DB_ADAPTER: mysql2
    RAILS_MAIL_DELIVERY_METHOD:
    RAILS_MAIL_DELIVERY_CONFIG:
    RAILS_MAIL_PERFORM_DELIVERIES:
    RAILS_MAIL_DOMAIN: pfadipatria.com
    RAILS_MAIL_RETRIEVER_TYPE: imap
    RAILS_MAIL_RETRIEVER_CONFIG:
    RAILS_SPHINX_PORT:
    RAILS_AIRBRAKE_API_KEY:
    RAILS_AIRBRAKE_HOST:
    RAILS_AIRBRAKE_PORT:
elasticsearch:
  image: elasticsearch
ambassador:
  image: svendowideit/ambassador
  links:
   - "mdb:mdb"
  ports:
   - "8081:80"
