mdb:
  image: pfadipatria/hitobito
  links:
   - thinkingsphinx:ts
  volumes_from:
   - thinkinglocalconf
  environment:
    RAILS_ENV: production
    RAILS_HOST_NAME: mdb-test.pfadipatria.com
    RAILS_HOST_SSL: false
    RAILS_SECRET_TOKEN:
    RAILS_DB_NAME: mdb_test
    RAILS_DB_USERNAME: mdb_test
    RAILS_DB_PASSWORD:
    RAILS_DB_HOST: mysql02
    RAILS_DB_PORT: 3306
    RAILS_DB_ADAPTER: mysql2
    RAILS_MAIL_DELIVERY_METHOD:
    RAILS_MAIL_DELIVERY_CONFIG:
    RAILS_MAIL_PERFORM_DELIVERIES:
    RAILS_MAIL_DOMAIN: pfadipatria.com
    RAILS_MAIL_RETRIEVER_TYPE: imap
    RAILS_MAIL_RETRIEVER_CONFIG:
    RAILS_SPHINX_PORT: 9312
    RAILS_AIRBRAKE_API_KEY:
    RAILS_AIRBRAKE_HOST:
    RAILS_AIRBRAKE_PORT:
    RAILS_LDAP_HOST:
    RAILS_LDAP_PORT:
    RAILS_LDAP_ATTRIBUTE:
    RAILS_LDAP_BASE:
    RAILS_LDAP_ADMIN_USER:
    RAILS_LDAP_ADMIN_PASSWORD:
    RAILS_LDAP_SSL:
thinkingsphinx:
  image: centurylink/sphinx:2.1.9.02
thinkinglocalconf:
  image: pfadipatria/ts-config
ambassador:
  image: svendowideit/ambassador
  links:
   - "mdb:mdb"
  ports:
   - "8081:80"
