mdb:
  image: pfadipatria/hitobito
  ports:
   - 80
  links:
   - elasticsearch:es
  env_file: /etc/mdb-prod.config
  environment:
    RAILS_ENV: production
    RAILS_HOST_NAME: mdb.pfadipatria.com
    RAILS_HOST_SSL: false
    RAILS_SECRET_TOKEN:
    RAILS_DB_NAME: mdb-prod
    RAILS_DB_USERNAME: mdb-prod
    RAILS_DB_PASSWORD:
    RAILS_DB_HOST: 
    RAILS_DB_PORT: 3306
    RAILS_DB_ADAPTER: mysql2
    RAILS_MAIL_DELIVERY_METHOD:
    RAILS_MAIL_DELIVERY_CONFIG:
    RAILS_MAIL_PERFORM_DELIVERIES:
    RAILS_MAIL_DOMAIN: pfadipatria.com
    RAILS_MAIL_RETRIEVER_TYPE: imap
    RAILS_MAIL_RETRIEVER_CONFIG:
    RAILS_SPHINX_PORT:
    RAILS_AIRBRAKE_API_KEY:
    RAILS_AIRBRAKE_HOST:
    RAILS_AIRBRAKE_PORT:
elasticsearch:
  image: elasticsearch
