mdb:
  extends:
    file: common.yml
    service: mdb
  volumes_from:
   - thinkinglocalconf
  links:
   - thinkingsphinx:ts
  ports:
   - "8083:80"
thinkingsphinx:
  extends:
    file: common.yml
    service: thinkingsphinx
  volumes_from:
   - thinkinglocalconf
thinkinglocalconf:
  extends:
    file: common.yml
    service: thinkinglocalconf
